require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe StatesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # State. As you add validations to State, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      code: 'CA',
      name: 'California',
    }
  end

  let(:invalid_attributes) do
    {
      code: 'CAAAA',
      name: 'California',
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      State.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      state = State.create! valid_attributes
      get :show, params: {id: state.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      state = State.create! valid_attributes
      get :edit, params: {id: state.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new State" do
        expect {
          post :create, params: {state: valid_attributes}, session: valid_session
        }.to change(State, :count).by(1)
      end

      it "redirects to the created state" do
        post :create, params: {state: valid_attributes}, session: valid_session
        expect(response).to redirect_to(State.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {state: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested state" do
        state = State.create! valid_attributes
        new_code = 'XY'
        put :update, params: {id: state.to_param, state: { code: new_code }}, session: valid_session
        state.reload
        expect(state.code).to eq new_code
      end

      it "redirects to the state" do
        state = State.create! valid_attributes
        put :update, params: {id: state.to_param, state: valid_attributes}, session: valid_session
        expect(response).to redirect_to(state)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        state = State.create! valid_attributes
        put :update, params: {id: state.to_param, state: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested state" do
      state = State.create! valid_attributes
      expect {
        delete :destroy, params: {id: state.to_param}, session: valid_session
      }.to change(State, :count).by(-1)
    end

    it "redirects to the states list" do
      state = State.create! valid_attributes
      delete :destroy, params: {id: state.to_param}, session: valid_session
      expect(response).to redirect_to(states_url)
    end
  end

end
